export const FETCH_USER = "FETCH_USER";
export const FETCH_GROUP_FEED = "FETCH_GROUP_FEED";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const FETCH_MENU_ITEMS = "FETCH_MENU_ITEMS";

export const SET_MENU_ITEM_TYPE = "SET_MENU_ITEM_TYPE";
export const SET_MENU_ITEM = "SET_MENU_ITEM";
export const SET_MENU_ITEM_OPTION = "SET_MENU_ITEM_OPTION";
export const ADD_CURRENT_ORDER_TO_CART = "ADD_CURRENT_ORDER_TO_CART";
export const MODIFY_ORDER = "MODIFY_ORDER";
export const POP_CART_ORDER = "POP_CART_ORDER";
export const SET_PAYMENT_INFO = "SET_PAYMENT_INFO";

export const SUBMIT_CART_ORDER = "SUBMIT_CART_ORDER";

export const FETCH_CART_ORDERS = "FETCH_CART_ORDERS";
export const SUCCESSFUL_SUBMIT_ORDER = "SUCCESSFUL_SUBMIT_ORDER";
export const FLAG_PRIORITY_ORDER = "FLAG_PRIORITY_ORDER";

// QUEUE
export const SET_TASK_STATUS = "SET_TASK_STATUS";
